### ISSUE TITLE
Fix mobile device support

### ISSUE THREAD

**Issue by ikeycode** [lispysnake/website#1]
More an ongoing issue but keep testing on mobile to ensure all is working ok.
The footer is bork, for example.

**Comment by ikeycode** [comment]
Mostly fixed - except intermittent issue with missing hamburger menu on some mobile devices. Can't recreate locally until synced to remote, so puzzled as af right

**Comment by ikeycode** [comment]
Footer fixed properly, still got hamburger issue.

**Comment by ryanleesipes** [comment]
Looked into this, seems to be an issue with the actual CSS for the button. Like you, I've had a hard time actually testing it on mobile :(

**Comment by ikeycode** [comment]
Too much farting around, dropped mdbootstrap for now.
